---
- name: Converge
  hosts: all
  become: true
  vars:
    easyrsa_pki_dir: /etc/easyrsa/pki
    easyrsa_servers:
      - name: server
    easyrsa_clients:
      - name: client1
      - name: client2
        pass: password
    easyrsa_renew: "{{ easyrsa_clients }}"
    easyrsa_revoked:
      - name: old_client
        reason: unspecified
    easyrsa_generate_dh: true
  roles:
    - role: easyrsa
