---

- name: Prepare
  hosts: all
  become: true
  vars:
    # Generate certificates to revoke during Converge
    easyrsa_pki_dir: /etc/easyrsa/pki
    easyrsa_clients:
      - name: old_client
  roles:
    - role: easyrsa
